# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# NOTE re open-pull-requests-limit.
#  - default is 5.
#  - setting to zero, not only default is 5.

version: 2
updates:
#  - package-ecosystem: "gitsubmodule"
#    directory: "/"
#    # - "deps/argo/"
#    # - "/deps/cryptol/"
#    # - "/deps/crucible/"
#    # Q. Is this only checking that submodule commit is out of date??
#    schedule:
#      interval: "weekly"
#    open-pull-requests-limit: 50
#      # default is 5.
    
#  - package-ecosystem: "github-actions"
#    directory: "/"
#    schedule:
#      # Check for updates to GitHub Actions every week
#      interval: "weekly"
#    open-pull-requests-limit: 50
#      # default is 5.
#
#  - package-ecosystem: "cargo"
#    directory: "/doc/rust-tutorial/code/salsa20"
#    schedule:
#      interval: "weekly"
#    open-pull-requests-limit: 50
#      # default is 5.

  - package-ecosystem: "pip"
    directories:
     - "/adhoc"
     # above is no good!
    schedule:
      interval: "weekly"

#   - package-ecosystem: "cargo"
#     directories:
#      - "/deps/crucible/crux-mir/lib/compiler_builtins"
#      - "/deps/crucible/crux-mir/report-coverage"
#     schedule:
#       interval: "weekly"
#     open-pull-requests-limit: 50
#       # default is 5.
