[package]
name = "rust-project"
version = "0.1.0"
edition = "2021"

[dependencies]
time = "0.1.12"
# ^ the above has a CVE (and is not overrode by `cargo build`).
# you can delete the above (the code does not depend upon) and confirm
# that `cargo audit` no longer gives an error

# libflate = "0.1.19"
# ^ this is libflate = "0.1.19"
